### ISSUE TITLE
Value of simplicity

### ISSUE THREAD

**Issue by mansoor2016** [mkirchner/linked-list-good-taste#4]
I agree that the indirect handle approach has a subjective beauty to it. 

There is also something to be said for code that can be understood with a cursory glance, and do not require explanations.

**Comment by DraTeots** [comment]
If you have 4 lines of code that require a TED talk and a GitHub repository to explain them... It points to some generic flaw, smell or whatever you call that feeling of something which not that elegant. 

P.S. And yes, the talk and the repo are not only an explanation but also a hymn to the "beauty" of those lines but you know what I meant.

**Comment by mkirchner** [comment]
@mansoor2016 and @DraTeots, I agree that there is a difference between code that is just elegant and code that is suitable for production!

> There is also something to be said for code that can be understood with a cursory glance, and do not require explanations.

For me, that's a function of my fluency and experience in a language. I am sure I would have grokked Linus' approach immediately if I were a better C programmer.

> If you have 4 lines of code that require a TED talk and a GitHub repository to explain them... It points to some generic flaw, smell or whatever you call that feeling of something which not that elegant.

To be fair, the TED talk is not explaining the code, it uses the code to explain what Linus Torvalds considers good code. But yes, if your and your peers' C experience does not match the experience of *the* Linux kernel developer, you probably should not be using this in production! ;-)

**Comment by DraTeots** [comment]
*"But yes, if your and your peers' C experience does not match the experience of the Linux kernel developer, you probably should not be using this in production! ;-)"* - you are so proud of them while one probably shouldn't be. It is like living in abusive environment and be proud of it (and many do, I know), proud of oneself about survival and endurance. While sane person would probably be happy not to live in such environment, try to avoid it and try to **improve / build better environment** for themselves if they live there for so many years.

**Comment by mkirchner** [comment]
@DraTeots, my apologies, this was a tounge-in-cheek comment. My point is that you need to adjust your code complexity to your environment and that that is a perfectly fine thing to do. No pride involved.
