### ISSUE TITLE
Code fails on null or item not in list.

### ISSUE THREAD

**Issue by TreyBoudreau** [mkirchner/linked-list-good-taste#5]
Both versions of the removal code fail when passed a null or non-existent target.

**Comment by johnnyvalles** [comment]
In addition, the code would also fail if the given target was not a pointer to a node that is present in the list but instead is a pointer to a node that was allocated for the purposes of searching.

For example:
```c
IntListItem *temp_target = malloc(sizeof(IntListItem));
target->value = 42;
target->next = NULL;

remove_elegant(someListHere, temp_target);

free(temp_target)
````

**Comment by glubsy** [comment]
I also thought the same: [this line](https://github.com/mkirchner/linked-list-good-taste/blob/main/src/list.c#L6) is potentially an infinite loop:
```c
void removecs_101(IntList* l, IntListItem* target) {
    InListItem *cur = l->head, *prev = NULL;
    while (cur != target) {
        prev = cur;
        cur = cur->next;
    }
    if (prev) {
        prev->next = cur->next;
    }
    else {
        l->head = cur->next;
    }
```
I suppose it could be rewritten like this? (I'm a complete newbie)
Also note the added comparison which was another issue:
```c
void removecs_101(IntList* l, IntListItem* target) {
    InListItem *cur = l->head, *prev = NULL;
    while (cur != target && cur != NULL) {
        prev = cur;
        cur = cur->next;
    }
    if (prev && cur == target) {
        prev->next = cur->next;
    }
    else if (l->head == target) {
        l->head = cur->next;
    }
```

Same for elegant:
```c
void remove_elegant(IntList *l, IntListItem *target) {
    IntListPointer **p = &l->head;
    while ((*p) != target && (*p)->next != NULL) {
        ...
```

**Comment by mkirchner** [comment]
@TreyBoudreau , @johnnyvalles, @glubsy you are all correct. The code is not checking its inputs since it's not relevant for the explanation how the indirect pointer works (neither does the code in Linus' example and I wanted to stay true to that).

**Comment by TreyBoudreau** [comment]
You should at least call out the fact that both functions have bugs, and fixing either of them makes them decidedly less elegant.

I’d like to add that I like and use the idiom advanced by Linus, but such code must execute correctly with a given API contract. For example, documenting the fact that the code will fail if passed nullptr or a pointer not in the list. Short of that, the code examples you’ve copied should never enter production.
